rvm:
  - 1.9.3
env:
  - DB=sqlite
  - DB=mysql
  - DB=postgresql

before_script:
	- "export DISPLAY=:99.0"
	- "sh -e /etc/init.d/xvfb start"
	- sleep 3 # give xvfb some time to start
	- rackup  # start a Web server
	- sleep 3 # give Web server some time to bind to sockets, etc
  - mysql -e 'create database myapp_test'
  - psql -c 'create database myapp_test' -U postgres

before_install:
  - "sudo apt-get update"
  - "sudo apt-get install libimage-exiftool-perl imagemagick wget ffmpeg zip unzip memcached" 

script:
  - RAILS_ENV=test bundle exec rake cucumber:ok --trace 